#include "\mrb_mod\script_component.hpp"

CLIENT_ONLY;

params ["_crate"];

_crate addAction ["Transfer Loadout", FNC(transferLoadout), [], 0.5, false, true, "", "true", 6];

["AmmoboxInit", [_crate]] spawn BIS_fnc_arsenal;

private _availableBackpacks = [
    // Ace gunbags
    "ace_gunbag",
    "ace_gunbag_tan",

    // Vanilla
    "B_Carryall_cbr",
    "B_Carryall_khk",
    "B_Kitbag_cbr",
    "B_Parachute",
    "B_AssaultPack_rgr",

    // RHS + Modified
    "506th_assault_eagleaiii_coy_Medic",
    "rhsusf_assault_eagleaiii_coy",

    // 3d MRB Backpacks
    "3d_assault_CM_SA",
    "3d_Assault_MEF_BL",
    "3d_Assault_MEF_CY",
    "3d_Assault_MEF_DM",
    "3d_Assault_MEF_M81",
    "3d_Assault_MEF_OD",
    "3d_Assault_MEF_TN",
    "3d_Assault_MEF_WM",
    "3d_assault_NWI_CY",
    "3d_assault_NWI_SA",
    "3d_assault_ST_CY",
    "3d_assault_WI_CY",
    "3d_assault_WI_SA",
    "3d_carryall_CM_CY",
    "3d_carryall_CM_SA",
    "3d_Carryall_MEF_BL",
    "3d_Carryall_MEF_CY",
    "3d_Carryall_MEF_DM",
    "3d_Carryall_MEF_M81",
    "3d_Carryall_MEF_TN",
    "3d_Carryall_MEF_OD",
    "3d_carryall_ST_SA",
    "3d_carryall_ST_CY",
    "3d_Carryall_MEF_WM",
    "3d_Kitbag_MEF_BL",
    "3d_Kitbag_MEF_CY",
    "3d_Kitbag_MEF_DM",
    "3d_Kitbag_MEF_M81",
    "3d_Kitbag_MEF_WM",
    "3d_Kitbag_MEF_TN",
    "3d_Kitbag_MEF_OD",
    "3d_largeruck_ST_SA",
    "3d_largeruck_ST_CY",
    "3d_Tactical_MEF_WM",
    "3d_Tactical_MEF_DM",
    "3d_Tactical_MEF_CY",

    // MILGP BackPacks
    "milgp_bp_marciras_Breacher_cb",
    "milgp_bp_marciras_Breacher_khk",
    "milgp_bp_marciras_Breacher_mc",
    "milgp_bp_marciras_Breacher_rgr",
    "milgp_bp_marciras_hydration_rgr",
    "milgp_bp_marciras_hydration_mc",
    "milgp_bp_marciras_hydration_khk",
    "milgp_bp_marciras_hydration_cb",
    "milgp_bp_marciras_Pointman_rgr",
    "milgp_bp_marciras_Pointman_mc",
    "milgp_bp_marciras_Pointman_khk",
    "milgp_bp_marciras_Pointman_cb",
    "milgp_bp_marciras_Tomahawk_rgr",
    "milgp_bp_marciras_Tomahawk_mc",
    "milgp_bp_marciras_Tomahawk_khk",
    "milgp_bp_marciras_Tomahawk_cb",

    // ILBE Radio's
    "tfw_ilbe_d",
    "tfw_ilbe_dd_d",
    "tfw_ilbe_blade_d",
    "tfw_ilbe_wd",
    "tfw_ilbe_dd_wd",
    "tfw_ilbe_blade_wd",
    "tfw_ilbe_dd_coy",
    "tfw_ilbe_coy"
];

// Helmets, Goggles, Uniform's, Vests, Items, Accessories
private _availableItemCargo = [
    // Helmets
    "rhsusf_hgu56p",
    "rhsusf_hgu56p_mask",
    "RHS_jetpilot_usaf",

    // MILGP Helmets
    "milgp_h_airframe_Combat_CB",
    "milgp_h_airframe_Combat_KHK",
    "milgp_h_airframe_Combat_rgr",
    "milgp_h_airframe_Light_CB",
    "milgp_h_airframe_Light_KHK",
    "milgp_h_airframe_Light_rgr",
    "milgp_h_airframe_tactical_CB",
    "milgp_h_airframe_tactical_KHK",
    "milgp_h_airframe_tactical_rgr",

    // SOCOM MICH
    "SOCOM_mich_bare_tan_brown",
    "SOCOM_mich_bare_tan_brown_headset",
    "SOCOM_mich_bare_tan_grey",
    "SOCOM_mich_bare_tan_grey_headset",
    "SOCOM_mich_bare_tan_sand",
    "SOCOM_mich_bare_tan_sand_headset",

    // SOCOM Fast
    "SOCOM_opscore_01_sof",
    "SOCOM_opscore_tb_pelt_cam_sof",
    "SOCOM_opscore_tb_pelt_nsw_cam_sof",
    "SOCOM_opscore_tb_pelt_nsw_sof",
    "SOCOM_opscore_tb_pelt_sof",
    "SOCOM_opscore_tb_sof",
    "SOCOM_opscore_th_pelt_cam_sof",
    "SOCOM_opscore_th_pelt_nsw_cam_sof",
    "SOCOM_opscore_th_pelt_nsw_sof",
    "SOCOM_opscore_th_pelt_sof",
    "SOCOM_opscore_th_sof",
    "SOCOM_opscore_ts_pelt_cam_sof",
    "SOCOM_opscore_ts_pelt_nsw_cam_sof",
    "SOCOM_opscore_ts_pelt_nsw_sof",
    "SOCOM_opscore_ts_pelt_sof",
    "SOCOM_opscore_ts_sof",

    // RHS Ops Core
    "rhsusf_opscore_01",
    "rhsusf_opscore_01_tan",
    "rhsusf_opscore_02",
    "rhsusf_opscore_02_tan",
    "rhsusf_opscore_aor1",
    "rhsusf_opscore_aor1_pelt",
    "rhsusf_opscore_aor1_pelt_nsw",
    "rhsusf_opscore_aor2",
    "rhsusf_opscore_aor2_pelt",
    "rhsusf_opscore_aor2_pelt_nsw",
    "rhsusf_opscore_bk",
    "rhsusf_opscore_bk_pelt",
    "rhsusf_opscore_cover",
    "rhsusf_opscore_coy_cover",
    "rhsusf_opscore_coy_cover_pelt",
    "rhsusf_opscore_fg",
    "rhsusf_opscore_fg_pelt",
    "rhsusf_opscore_fg_pelt_cam",
    "rhsusf_opscore_fg_pelt_nsw",
    "rhsusf_opscore_paint",
    "rhsusf_opscore_paint_pelt",
    "rhsusf_opscore_paint_pelt_nsw",
    "rhsusf_opscore_paint_pelt_nsw_cam",
    "rhsusf_opscore_rg_cover",
    "rhsusf_opscore_rg_cover_pelt",
    "rhsusf_opscore_ut",
    "rhsusf_opscore_ut_pelt",
    "rhsusf_opscore_ut_pelt_cam",
    "rhsusf_opscore_ut_pelt_nsw",
    "rhsusf_opscore_ut_pelt_nsw_cam",

    // RHS MICH 2000
    "rhsusf_mich_bare",
    "rhsusf_mich_bare_alt",
    "rhsusf_mich_bare_alt_semi",
    "rhsusf_mich_bare_alt_tan",
    "rhsusf_mich_bare_headset",
    "rhsusf_mich_bare_norotos",
    "rhsusf_mich_bare_norotos_alt",
    "rhsusf_mich_bare_norotos_alt_headset",
    "rhsusf_mich_bare_norotos_alt_semi",
    "rhsusf_mich_bare_norotos_alt_semi_headset",
    "rhsusf_mich_bare_norotos_alt_tan",
    "rhsusf_mich_bare_norotos_alt_tan_headset",
    "rhsusf_mich_bare_norotos_arc",
    "rhsusf_mich_bare_norotos_arc_alt",
    "rhsusf_mich_bare_norotos_arc_alt_headset",
    "rhsusf_mich_bare_norotos_arc_alt_semi",
    "rhsusf_mich_bare_norotos_arc_alt_semi_headset",
    "rhsusf_mich_bare_norotos_arc_alt_tan",
    "rhsusf_mich_bare_norotos_arc_alt_tan_headset",
    "rhsusf_mich_bare_norotos_arc_headset",
    "rhsusf_mich_bare_norotos_arc_semi",
    "rhsusf_mich_bare_norotos_arc_semi_headset",
    "rhsusf_mich_bare_norotos_arc_tan",
    "rhsusf_mich_bare_norotos_arc_tan_headset",
    "rhsusf_mich_bare_norotos_headset",
    "rhsusf_mich_bare_norotos_semi",
    "rhsusf_mich_bare_norotos_semi_headset",
    "rhsusf_mich_bare_norotos_tan",
    "rhsusf_mich_bare_norotos_tan_headset",
    "rhsusf_mich_bare_semi",
    "rhsusf_mich_bare_semi_headset",
    "rhsusf_mich_bare_tan",

    // Goggles
    "G_Shades_Black",
    "G_Shades_Blue",
    "G_Shades_Green",
    "G_Shades_Red",
    "G_Spectacles_Tinted",
    "G_Lowprofile",
    "rhs_googles_clear",
    "rhs_googles_orange",
    "rhs_googles_yellow",
    "rhs_googles_black",
    "rhs_ess_black",
    "G_B_Diving",

    // Uniforms
    "U_B_HeliPilotCoveralls",
    "U_B_Wetsuit",

    // SOCOM Uniforms
    "SOCOM_uniform_g3_m81_base",
    "SOCOM_uniform_g3_dcu_base",
    "SOCOM_uniform_g3_bdu_base",
    "SOCOM_uniform_g3_d_marpat_base",
    "SOCOM_uniform_g3_w_marpat_base",
    "Gen3_Ranger",
    "Gen3_Tan",

    //Vests
    "V_TacVest_oli",
    "V_RebreatherB",

    // JPC MILGP
    // MILGP JPC Assaulter
    "milgp_v_jpc_assaulter_belt_cb",
    "milgp_v_jpc_assaulter_belt_khk",
    "milgp_v_jpc_assaulter_belt_mc",
    "milgp_v_jpc_assaulter_belt_rgr",
    "milgp_v_jpc_assaulter_cb",
    "milgp_v_jpc_assaulter_khk",
    "milgp_v_jpc_assaulter_mc",
    "milgp_v_jpc_assaulter_rgr",

    // MILGP JPC Grenadier
    "milgp_v_jpc_Grenadier_belt_cb",
    "milgp_v_jpc_Grenadier_belt_khk",
    "milgp_v_jpc_Grenadier_belt_mc",
    "milgp_v_jpc_Grenadier_belt_rgr",
    "milgp_v_jpc_Grenadier_cb",
    "milgp_v_jpc_Grenadier_khk",
    "milgp_v_jpc_Grenadier_mc",
    "milgp_v_jpc_Grenadier_rgr",

    // MILGP JPC Heavy Gunner
    "milgp_v_jpc_hgunner_belt_cb",
    "milgp_v_jpc_hgunner_belt_khk",
    "milgp_v_jpc_hgunner_belt_mc",
    "milgp_v_jpc_hgunner_belt_rgr",
    "milgp_v_jpc_hgunner_cb",
    "milgp_v_jpc_hgunner_khk",
    "milgp_v_jpc_hgunner_mc",
    "milgp_v_jpc_hgunner_rgr",

    // MILGP JPC Marksman
    "milgp_v_jpc_marksman_belt_cb",
    "milgp_v_jpc_marksman_belt_khk",
    "milgp_v_jpc_marksman_belt_mc",
    "milgp_v_jpc_marksman_belt_rgr",
    "milgp_v_jpc_Marksman_cb",
    "milgp_v_jpc_Marksman_khk",
    "milgp_v_jpc_Marksman_mc",
    "milgp_v_jpc_Marksman_rgr",

    // MILGP JPC Medic
    "milgp_v_jpc_medic_belt_cb",
    "milgp_v_jpc_medic_belt_khk",
    "milgp_v_jpc_medic_belt_mc",
    "milgp_v_jpc_medic_belt_rgr",
    "milgp_v_jpc_Medic_cb",
    "milgp_v_jpc_Medic_khk",
    "milgp_v_jpc_Medic_mc",
    "milgp_v_jpc_Medic_rgr",

    // MILGP JPC Teamleader
    "milgp_v_jpc_teamleader_belt_cb",
    "milgp_v_jpc_teamleader_belt_khk",
    "milgp_v_jpc_teamleader_belt_mc",
    "milgp_v_jpc_teamleader_belt_rgr",
    "milgp_v_jpc_TeamLeader_cb",
    "milgp_v_jpc_TeamLeader_khk",
    "milgp_v_jpc_TeamLeader_mc",
    "milgp_v_jpc_TeamLeader_rgr",

    // Marciras MILGP Assaulter
    "milgp_v_marciras_assaulter_belt_cb",
    "milgp_v_marciras_assaulter_belt_khk",
    "milgp_v_marciras_assaulter_belt_mc",
    "milgp_v_marciras_assaulter_belt_rgr",
    "milgp_v_marciras_assaulter_cb",
    "milgp_v_marciras_assaulter_khk",
    "milgp_v_marciras_assaulter_mc",
    "milgp_v_marciras_assaulter_rgr",

    // MilGP Marciras Grenadier
    "milgp_v_marciras_grenadier_belt_cb",
    "milgp_v_marciras_grenadier_belt_khk",
    "milgp_v_marciras_grenadier_belt_mc",
    "milgp_v_marciras_grenadier_belt_rgr",
    "milgp_v_marciras_grenadier_cb",
    "milgp_v_marciras_grenadier_khk",
    "milgp_v_marciras_grenadier_mc",
    "milgp_v_marciras_grenadier_rgr",

    // MilGP Marciras Heavy Gunner
    "milgp_v_marciras_hgunner_belt_cb",
    "milgp_v_marciras_hgunner_belt_khk",
    "milgp_v_marciras_hgunner_belt_mc",
    "milgp_v_marciras_hgunner_belt_rgr",
    "milgp_v_marciras_hgunner_cb",
    "milgp_v_marciras_hgunner_khk",
    "milgp_v_marciras_hgunner_mc",
    "milgp_v_marciras_hgunner_rgr",

    // MilGP Marciras Marksman
    "milgp_v_marciras_marksman_belt_cb",
    "milgp_v_marciras_marksman_belt_khk",
    "milgp_v_marciras_marksman_belt_mc",
    "milgp_v_marciras_marksman_belt_rgr",
    "milgp_v_marciras_marksman_cb",
    "milgp_v_marciras_marksman_khk",
    "milgp_v_marciras_marksman_mc",
    "milgp_v_marciras_marksman_rgr",

    // MilGP Marciras Medic
    "milgp_v_marciras_medic_belt_cb",
    "milgp_v_marciras_medic_belt_khk",
    "milgp_v_marciras_medic_belt_mc",
    "milgp_v_marciras_medic_belt_rgr",
    "milgp_v_marciras_medic_cb",
    "milgp_v_marciras_medic_khk",
    "milgp_v_marciras_medic_mc",
    "milgp_v_marciras_medic_rgr",

    // MilGP Marciras Teamleader
    "milgp_v_marciras_teamleader_belt_CB",
    "milgp_v_marciras_teamleader_belt_KHK",
    "milgp_v_marciras_teamleader_belt_mc",
    "milgp_v_marciras_teamleader_belt_RGR",
    "milgp_v_marciras_teamleader_CB",
    "milgp_v_marciras_teamleader_KHK",
    "milgp_v_marciras_teamleader_mc",
    "milgp_v_marciras_teamleader_RGR",

    // Ace Items
    // Basic Medical
    "ACE_bloodIV_250",
    "ACE_epinephrine",
    "ACE_fieldDressing",
    "ACE_morphine",

    // Advanced Medical
    "ACE_atropine",
    "ACE_elasticBandage",
    "ACE_quikclot",
    "ACE_bloodIV",
    "ACE_bloodIV_500",
    "ACE_packingBandage",
    "ACE_personalAidKit",
    "ACE_plasmaIV",
    "ACE_plasmaIV_500",
    "ACE_plasmaIV_250",
    "ACE_salineIV",
    "ACE_salineIV_500",
    "ACE_salineIV_250",
    "ACE_tourniquet",
    "ACE_surgicalKit",

    // Ace Items
    "ACE_SpraypaintBlack",
    "ACE_SpraypaintBlue",
    "ACE_SpraypaintGreen",
    "ACE_SpraypaintRed",
    "ACE_TacticalLadder_Item",
    "ACE_Tripod",
    "ACE_UAVBattery",
    "ACE_wirecutter",
    "ACE_Flashlight_MX991",
    "ACE_HuntIR_monitor",
    "ACE_Kestrel4500",
    "ACE_M26_Clacker",
    "ACE_MapTools",
    "ACE_Altimeter",
    "ACE_CableTie",
    "ACE_Clacker",
    "ACE_DefusalKit",
    "ACE_EarPlugs",
    "ACE_EntrenchingTool",
    "ACE_VectorDay",
    "ACE_Vector",
    "ACE_muzzle_mzls_smg_01",

    // NVGs
    "rhsusf_Rhino",
    "rhsusf_ANPVS_14",
    "rhsusf_ANPVS_15",
    "rhsusf_ANPVS_15_ng",
    "rhsusf_ANPVS_14_full",
    "rhsusf_ANPVS_15_full",
    "rhsusf_ANPVS_14_oval",
    "rhsusf_ANPVS_14_full_ng",
    "rhsusf_ANPVS_15_full_ng",
    "rhsusf_ANPVS_14_oval_ng",

    // CTAB
    "ItemAndroid",
    "ItemMicroDAGR",
    "ItemcTab",
    "ItemcTabHCam",

    // Vanilla Items
    "ItemWatch",
    "ItemGPS",
    "ItemMap",
    "ItemCompass",
    "B_UavTerminal",
    "MineDetector",
    "TIAD_506th_UAV_Item",
    "ToolKit",
    //"ItemRadio",
    "tf_anprc152",
    "Laserdesignator",
    "Laserbatteries",

    // SMA Optics and Attachments
    "SMA_ANPEQ15_BLK",
    "SMA_ANPEQ15_TAN",
    "SMA_ANPEQ15_TOP_417BLK",
    "SMA_ANPEQ15_TOP_417TAN",
    "SMA_ANPEQ15_TOP_BLK",
    "SMA_ANPEQ15_TOP_BLK_ACR",
    "SMA_ANPEQ15_TOP_BLK_M4",
    "SMA_ANPEQ15_TOP_BLK_MK18",
    "SMA_ANPEQ15_TOP_BLK_SCAR",
    "SMA_ANPEQ15_TOP_TAN",
    "SMA_ANPEQ15_TOP_TAN_ACR",
    "SMA_ANPEQ15_TOP_TAN_M4",
    "SMA_ANPEQ15_TOP_TAN_MK18",
    "SMA_ANPEQ15_TOP_TAN_SCAR",
    "SMA_ELCAN_SPECTER_4z",
    "SMA_ELCAN_SPECTER_ARDRDS_4z",
    "SMA_ELCAN_SPECTER_GREEN_4z",
    "SMA_ELCAN_SPECTER_GREEN_ARDRDS_4z",
    "SMA_ELCAN_SPECTER_GREEN_RDS_4z",
    "SMA_ELCAN_SPECTER_GREEN3_4z",
    "SMA_ELCAN_SPECTER_GREEN3_ARDRDS_4z",
    "SMA_ELCAN_SPECTER_GREEN3_RDS_4z",
    "SMA_ELCAN_SPECTER_GREEN5_4z",
    "SMA_ELCAN_SPECTER_GREEN5_ARDRDS_4z",
    "SMA_ELCAN_SPECTER_GREEN5_RDS_4z",
    "SMA_ELCAN_SPECTER_GREEN6_4z",
    "SMA_ELCAN_SPECTER_GREEN6_ARDRDS_4z",
    "SMA_ELCAN_SPECTER_GREEN6_RDS_4z",
    "SMA_ELCAN_SPECTER_RDS_4z",
    "SMA_ELCAN_SPECTER_TAN_4z",
    "SMA_ELCAN_SPECTER_TAN_ARDRDS_4z",
    "SMA_ELCAN_SPECTER_TAN_RDS_4z",
    "SMA_ELCAN_SPECTER_TAN3_4z",
    "SMA_ELCAN_SPECTER_TAN3_ARDRDS_4z",
    "SMA_ELCAN_SPECTER_TAN3_RDS_4z",
    "SMA_ELCAN_SPECTER_TAN5_4z",
    "SMA_ELCAN_SPECTER_TAN5_ARDRDS_4z",
    "SMA_ELCAN_SPECTER_TAN5_RDS_4z",
    "SMA_ELCAN_SPECTER_TAN6_4z",
    "SMA_ELCAN_SPECTER_TAN6_ARDRDS_4z",
    "SMA_ELCAN_SPECTER_TAN6_RDS_4z",
    "SMA_ELCAN_SPECTER3_4z",
    "SMA_ELCAN_SPECTER3_ARDRDS_4z",
    "SMA_ELCAN_SPECTER3_RDS_4z",
    "SMA_ELCAN_SPECTER5_4z",
    "SMA_ELCAN_SPECTER5_ARDRDS_4z",
    "SMA_ELCAN_SPECTER5_RDS_4z",
    "SMA_ELCAN_SPECTER6_4z",
    "SMA_ELCAN_SPECTER6_ARDRDS_4z",
    "SMA_ELCAN_SPECTER6_RDS_4z",
    "SMA_eotech",
    "SMA_eotech_G",
    "SMA_eotech_T",
    "SMA_eotech552",
    "SMA_eotech552_3XDOWN",
    "SMA_eotech552_3XDOWN_des",
    "SMA_eotech552_3XDOWN_wdl",
    "SMA_eotech552_3XUP",
    "SMA_eotech552_3XUP_des",
    "SMA_eotech552_3XUP_wdl",
    "SMA_eotech552_kf",
    "SMA_eotech552_kf_des",
    "SMA_eotech552_kf_wdl",
    "SMA_eotechG33_3XDOWN",
    "SMA_eotechG33_3XUP",
    "SMA_eotechG33_grn_3XDOWN",
    "SMA_eotechG33_grn_3XUP",
    "SMA_eotechG33_tan_3XDOWN",
    "SMA_eotechG33_tan_3XUP",
    "SMA_FLASHHIDER1",
    "SMA_FLASHHIDER2",
    "SMA_Gripod_01",
    "SMA_MICRO_T2",
    "SMA_MICRO_T2_3XDOWN",
    "SMA_MICRO_T2_3XUP",
    "SMA_MICRO_T2_LM",
    "SMA_rotex_blk",
    "SMA_rotex_gry",
    "SMA_rotex_tan",
    "SMA_SFFL_BLK",
    "SMA_SFFL_TAN",
    "SMA_SFLIGHT_TOPM4",
    "SMA_SFPEQ_ACRTOP_BLK",
    "SMA_SFPEQ_ACRTOP_BLK_LIGHT",
    "SMA_SFPEQ_ACRTOP_TAN",
    "SMA_SFPEQ_ACRTOP_TAN_LIGHT",
    "SMA_SFPEQ_AUGCQC_BLK",
    "SMA_SFPEQ_AUGCQC_BLK_LIGHT",
    "SMA_SFPEQ_AUGCQC_TAN",
    "SMA_SFPEQ_AUGCQC_TAN_LIGHT",
    "SMA_SFPEQ_HK417TOP_BLK",
    "SMA_SFPEQ_HK417TOP_BLK_LIGHT",
    "SMA_SFPEQ_HK417TOP_TAN",
    "SMA_SFPEQ_HK417TOP_TAN_LIGHT",
    "SMA_SFPEQ_HKTOP_BLK",
    "SMA_SFPEQ_HKTOP_BLK_LIGHT",
    "SMA_SFPEQ_HKTOP_TAN",
    "SMA_SFPEQ_HKTOP_TAN_LIGHT",
    "SMA_SFPEQ_M4TOP_BLK",
    "SMA_SFPEQ_M4TOP_BLK_LIGHT",
    "SMA_SFPEQ_M4TOP_TAN",
    "SMA_SFPEQ_M4TOP_TAN_LIGHT",
    "SMA_SFPEQ_MK18TOP_BLK",
    "SMA_SFPEQ_MK18TOP_BLK_LIGHT",
    "SMA_SFPEQ_MK18TOP_TAN",
    "SMA_SFPEQ_MK18TOP_TAN_LIGHT",
    "SMA_SFPEQ_SCARTOP_BLK",
    "SMA_SFPEQ_SCARTOP_BLK_LIGHT",
    "SMA_SFPEQ_SCARTOP_TAN",
    "SMA_SFPEQ_SCARTOP_TAN_LIGHT",
    "SMA_Silencer_556",
    "SMA_Silencer_556_Bronze",
    "SMA_Silencer_556_Silver",
    "sma_spitfire_01_black",
    "sma_spitfire_01_green",
    "sma_spitfire_01_red",
    "sma_spitfire_01_sc_black",
    "sma_spitfire_01_sc_closed",
    "sma_spitfire_01_sc_green",
    "sma_spitfire_01_sc_red",
    "sma_spitfire_03_black",
    "sma_spitfire_03_green",
    "sma_spitfire_03_rds_black",
    "sma_spitfire_03_rds_green",
    "sma_spitfire_03_rds_low_ard_black",
    "sma_spitfire_03_rds_low_ard_green",
    "sma_spitfire_03_rds_low_ard_red",
    "sma_spitfire_03_rds_low_black",
    "sma_spitfire_03_rds_low_green",
    "sma_spitfire_03_rds_low_red",
    "sma_spitfire_03_rds_red",
    "sma_spitfire_03_red",
    "sma_spitfire_03_sc_black",
    "sma_spitfire_03_sc_closed",
    "sma_spitfire_03_sc_green",
    "sma_spitfire_03_sc_red",
    "SMA_supp_762",
    "SMA_supp1b_556",
    "SMA_supp1BB_556",
    "SMA_supp1BOD_556",
    "SMA_supp1BT_556",
    "SMA_supp1Bwht_556",
    "SMA_supp1tan_556",
    "SMA_supp1TB_556",
    "SMA_supp1TOD_556",
    "SMA_supp1TT_556",
    "SMA_supp1TW_556",
    "SMA_supp2b_556",
    "SMA_supp2BOD_556",
    "SMA_supp2BT_556",
    "SMA_supp2btan_556",
    "SMA_supp2BW_556",
    "SMA_supp2smaB_556",
    "SMA_supp2smaT_556",
    "SMA_supp2T_556",
    "SMA_supp2TB_556",
    "SMA_supp2TOD_556",
    "SMA_supp2TWH_556",
    "SMA_supptan_762",

    // Weapon Accessories
    "muzzle_snds_acp",
    "FHQ_optic_LeupoldERT",
    "FHQ_optic_LeupoldERT_tan",
    "optic_LRPS",
    "rhsusf_acc_LEUPOLDMK4",
    "rhsusf_acc_LEUPOLDMK4_2",
    "rhsusf_acc_LEUPOLDMK4_2_d",
    "acc_pointer_IR",
    "rhsusf_acc_anpeq15",
    "rhsusf_acc_anpeq15A",
    "rhsusf_acc_anpeq15_light",
    "rhsusf_acc_anpeq15side",
    "rhsusf_acc_anpeq15_top",
    "rhsusf_acc_anpeq15side_bk",
    "rhsusf_acc_anpeq15_bk_top",
    "rhsusf_acc_anpeq15_bk",
    "rhsusf_acc_anpeq15_bk_light",
    "rhsusf_acc_ACOG_USMC",
    "rhsusf_acc_ACOG2_USMC",
    "rhsusf_acc_ACOG3_USMC",
    "rhsusf_acc_compm4",
    "rhsusf_acc_ELCAN",
    "FHQ_optic_ACOG",
    "FHQ_optic_AimM_BLK",
    "FHQ_optic_AC11704",
    "FHQ_optic_TWS3050",
    "optic_tws",
    "optic_tws_mg",
    "rhsusf_acc_premier_anpvs27",
    "rhsusf_acc_premier",
    "rhsusf_acc_harris_bipod",
    "rhsusf_acc_grip1",
    "rhsusf_acc_grip2",
    "rhsusf_acc_grip3",
    "rhsusf_acc_SF3P556",
    "rhs_weap_optic_smaw",
    "tf47_optic_m3maaws",
    "tfw_rf3080Item"
];

// Magazines, Ammo, Grenades
private _availableMagazines = [

    // RHS Marksman Magazines
    // M107
    "rhsusf_mag_10Rnd_STD_50BMG_M33",
    "rhsusf_mag_10Rnd_STD_50BMG_mk211",
    //  M24
    "rhsusf_5Rnd_762x51_m118_special_Mag",
    "rhsusf_5Rnd_762x51_m62_Mag",
    "rhsusf_5Rnd_762x51_m993_Mag",
    // Mk. 11 Mod 0
    "rhsusf_20Rnd_762x51_m118_special_Mag",
    "rhsusf_20Rnd_762x51_m993_Mag",
    "rhsusf_20Rnd_762x51_m62_Mag",

    // SMA Minimi MK3 Magazines
    "SMA_150Rnd_762_M80A1",
    "SMA_150Rnd_762_M80A1_Tracer",
    "SMA_150Rnd_762_M80A1_Mixed",

    // SMA M4A1 - MK 18 - SCAR L Magazines
    "SMA_30Rnd_556x45_M855A1",
    "SMA_30Rnd_556x45_M855A1_Tracer",
    "SMA_30Rnd_556x45_M855A1_IR",
    "SMA_30Rnd_556x45_Mk318",
    "SMA_30Rnd_556x45_Mk318_Tracer",
    "SMA_30Rnd_556x45_Mk318_IR",
    "SMA_30Rnd_556x45_Mk262",
    "SMA_30Rnd_556x45_Mk262_Tracer",
    "SMA_30Rnd_556x45_Mk262_IR",

    // SMA SCAR H Magazines
    "SMA_20Rnd_762x51mm_M80A1_EPR",
    "SMA_20Rnd_762x51mm_M80A1_EPR_Tracer",
    "SMA_20Rnd_762x51mm_M80A1_EPR_IR",
    "SMA_20Rnd_762x51mm_Mk316_Mod_0_Special_Long_Range",
    "SMA_20Rnd_762x51mm_Mk316_Mod_0_Special_Long_Range_Tracer",
    "SMA_20Rnd_762x51mm_Mk316_Mod_0_Special_Long_Range_IR",
    "SMA_20Rnd_762x51mm_Lapua_FMJ_Subsonic",
    "SMA_20Rnd_762x51mm_Lapua_FMJ_Subsonic_Tracer",
    "SMA_20Rnd_762x51mm_Lapua_FMJ_Subsonic_IR",

    // Carl Gustov Ammo
    "tf47_m3maaws_HEAT",
    "tf47_m3maaws_HEDP",
    "tf47_m3maaws_HE",
    "tf47_m3maaws_SMOKE",
    "tf47_m3maaws_ILLUM",

    // Pistol Magazines
    // Glock 17 Magazines
    "rhsusf_mag_17Rnd_9x19_FMJ",
    "rhsusf_mag_17Rnd_9x19_JHP",
    // M1911 Magazine
    "rhsusf_mag_7x45acp_MHP",
    // m9 Beretta Magazines
    "rhsusf_mag_15Rnd_9x19_JHP",
    "rhsusf_mag_15Rnd_9x19_FMJ",
    // Custom Covert II
    "9Rnd_45ACP_Mag",

    // MISC Items
    "rhs_mag_30Rnd_556x45_Mk318_Stanag",
    "ACE_HuntIR_M203",
    "rhs_mag_M433_HEDP",
    "rhs_mag_M441_HE",
    "rhs_mag_m4009",
    "rhs_mag_m576",
    "rhs_mag_M585_white",
    "rhs_mag_m661_green",
    "rhs_mag_m662_red",
    "rhs_mag_m713_Red",
    "rhs_mag_m714_White",
    "rhs_mag_m715_Green",
    "rhs_mag_m716_yellow",
    "rhsusf_100Rnd_762x51",
    "rhsusf_100Rnd_762x51_m993",
    "rhsusf_100Rnd_556x45_soft_pouch",
    "rhsusf_200Rnd_556x45_soft_pouch",
    "rhs_200rnd_556x45_M_SAW",
    "rhsusf_5Rnd_00Buck",
    "rhsusf_5Rnd_Slug",
    "rhsusf_8Rnd_00Buck",
    "rhsusf_8Rnd_Slug",
    "rhs_m136_mag",
    "rhs_m136_hp_mag",
    "rhs_m136_hedp_mag",
    "rhs_mag_smaw_HEAA",
    "rhs_mag_smaw_HEDP",
    "rhs_mag_smaw_SR",
    "rhs_m72a7_mag",
    "rhsusf_mag_6Rnd_M585_white",
    "rhsusf_mag_6Rnd_m661_green",
    "rhsusf_mag_6Rnd_m662_red",
    "rhsusf_mag_6Rnd_M713_red",
    "rhsusf_mag_6Rnd_M714_white",
    "rhsusf_mag_6Rnd_M715_green",
    "rhsusf_mag_6Rnd_M716_yellow",
    "DemoCharge_Remote_Mag",
    "SatchelCharge_Remote_Mag",
    "ClaymoreDirectionalMine_Remote_Mag",
    "ATMine_Range_Mag",
    "SLAMDirectionalMine_Wire_Mag",
    "APERSBoundingMine_Range_Mag",
    "ACE_HandFlare_Green",
    "ACE_HandFlare_Red",
    "ACE_HandFlare_White",
    "ACE_HandFlare_Yellow",
    "rhs_mag_mk84",
    "HandGrenade",
    "B_IR_Grenade",
    "SmokeShell",
    "SmokeShellRed",
    "SmokeShellGreen",
    "SmokeShellYellow",
    "SmokeShellPurple",
    "SmokeShellBlue",
    "SmokeShellOrange",
    "Chemlight_green",
    "Chemlight_red",
    "Chemlight_blue",
    "Chemlight_yellow"
];

// Weapons
private _availableWeapons = [
    // SMA M4 Variants
    "SMA_M4_GL",
    "SMA_M4_GL_SM",
    "SMA_M4afg",
    "SMA_M4afg_BLK1",
    "SMA_M4afg_BLK1_SM",
    "SMA_M4afg_OD",
    "SMA_M4afg_OD_SM",
    "SMA_M4afg_SM",
    "SMA_M4afg_Tan",
    "SMA_M4afg_Tan_SM",
    "SMA_M4afgSTOCK",
    "SMA_M4CQBR",
    "SMA_M4CQBRMOE",
    "SMA_M4MOE",
    "SMA_M4MOE_BLK1",
    "SMA_M4MOE_BLK1_SM",
    "SMA_M4MOE_OD",
    "SMA_M4MOE_OD_SM",
    "SMA_M4MOE_SM",
    "SMA_M4MOE_Tan",
    "SMA_M4MOE_Tan_SM",
    "SMA_MICRO_T2",
    "SMA_MICRO_T2_3XDOWN",
    "SMA_MICRO_T2_3XUP",
    "SMA_MICRO_T2_LM",

    // SMA Minimi Mk3
    "sma_minimi_mk3_762tlb",
    "sma_minimi_mk3_762tlb_des",
    "sma_minimi_mk3_762tlb_wdl",
    "sma_minimi_mk3_762tsb",
    "sma_minimi_mk3_762tsb_des",
    "sma_minimi_mk3_762tsb_wdl",

    // SMA MK18
    "SMA_MK18_GL",
    "SMA_MK18_GL_SM",
    "SMA_MK18afg",
    "SMA_MK18afg_SM",
    "SMA_MK18afgBLK",
    "SMA_MK18afgBLK_SM",
    "SMA_MK18afgOD",
    "SMA_MK18afgOD_SM",
    "SMA_MK18afgODBLK",
    "SMA_MK18afgODBLK_SM",
    "SMA_MK18afgTAN",
    "SMA_MK18afgTAN_SM",
    "SMA_MK18afgTANBLK",
    "SMA_MK18afgTANBLK_SM",
    "SMA_MK18BLK_GL",
    "SMA_MK18BLK_GL_SM",
    "SMA_MK18MOE",
    "SMA_MK18MOE_SM",
    "SMA_MK18MOEBLK",
    "SMA_MK18MOEBLK_SM",
    "SMA_MK18MOEBLKTAN",
    "SMA_MK18MOEBLKTAN_SM",
    "SMA_MK18MOEOD",
    "SMA_MK18MOEOD_SM",
    "SMA_MK18MOEODBLK",
    "SMA_MK18MOEODBLK_SM",
    "SMA_MK18MOETAN",
    "SMA_MK18MOETAN_SM",
    "SMA_MK18OD_GL",
    "SMA_MK18OD_GL_SM",
    "SMA_MK18ODBLK_GL",
    "SMA_MK18ODBLK_GL_SM",
    "SMA_MK18TAN_GL",
    "SMA_MK18TAN_GL_SM",
    "SMA_MK18TANBLK_GL",
    "SMA_MK18TANBLK_GL_SM",

    // RHS M107
    "rhs_weap_M107",
    "rhs_weap_M107_d",
    "rhs_weap_M107_w",

    // RHS M24
    "rhs_weap_m24sws",
    "rhs_weap_m24sws_blk",
    "rhs_weap_m24sws_ghillie",

    // SMA MK17
    "SMA_Mk17",
    "SMA_Mk17_16",
    "SMA_Mk17_16_black",
    "SMA_Mk17_16_Green",
    "SMA_Mk17_black",
    "SMA_Mk17_EGLM",
    "SMA_MK17_EGLM_black",
    "SMA_MK17_EGLM_Green",
    "SMA_Mk17_Green",

    // SMA MK16
    "SMA_MK16",
    "SMA_Mk16_black",
    "SMA_Mk16_blackQCB",
    "SMA_Mk16_EGLM",
    "SMA_MK16_EGLM_black",
    "SMA_MK16_EGLM_Green",
    "SMA_Mk16_Green",
    "SMA_Mk16_GreenQCB",
    "SMA_Mk16QCB",

    // TF47 M3 MAAWS
    "tf47_m3maaws",

    // RHS M4A1 Block II
    "rhs_weap_m4a1_blockII",
    "rhs_weap_m4a1_blockII_bk",
    "rhs_weap_m4a1_blockII_d",
    "rhs_weap_m4a1_blockII_grip",
    "rhs_weap_m4a1_blockII_grip_bk",
    "rhs_weap_m4a1_blockII_grip_d",
    "rhs_weap_m4a1_blockII_grip_KAC",
    "rhs_weap_m4a1_blockII_grip_KAC_bk",
    "rhs_weap_m4a1_blockII_grip_KAC_d",
    "rhs_weap_m4a1_blockII_grip_KAC_wd",
    "rhs_weap_m4a1_blockII_grip2",
    "rhs_weap_m4a1_blockII_grip_wd",
    "rhs_weap_m4a1_blockII_grip2_KAC_bk",
    "rhs_weap_m4a1_blockII_grip2_KAC",
    "rhs_weap_m4a1_blockII_grip2_d",
    "rhs_weap_m4a1_blockII_grip2_bk",
    "rhs_weap_m4a1_blockII_KAC",
    "rhs_weap_m4a1_blockII_grip2_wd",
    "rhs_weap_m4a1_blockII_grip2_KAC_wd",
    "rhs_weap_m4a1_blockII_grip2_KAC_d",
    "rhs_weap_m4a1_blockII_KAC_SU230_sup",
    "rhs_weap_m4a1_blockII_KAC_SU230",
    "rhs_weap_m4a1_blockII_KAC_d",
    "rhs_weap_m4a1_blockII_KAC_bk",
    "rhs_weap_m4a1_blockII_M203_d",
    "rhs_weap_m4a1_blockII_M203_bk",
    "rhs_weap_m4a1_blockII_M203",
    "rhs_weap_m4a1_blockII_KAC_wd",
    "rhs_weap_m4a1_blockII_wd",
    "rhs_weap_m4a1_blockII_M203_wd",
    "rhs_weap_m4a1_blockII_M203_SU230",

    // RHS Mk 11 Mod 0
    "rhs_weap_sr25",
    "rhs_weap_sr25_d",
    "rhs_weap_sr25_ec",
    "rhs_weap_sr25_ec_d",
    "rhs_weap_sr25_ec_wd",
    "rhs_weap_sr25_sup_marsoc",
    "rhs_weap_sr25_sup_usmc",
    "rhs_weap_sr25_usmc",
    "rhs_weap_sr25_wd",

    // MISC Weapons
    "rhs_weap_m249_pip_S",
    "rhs_weap_m249_pip_S_para",
    "rhs_weap_m249_pip_S_vfg",
    "rhs_weap_m249_pip_L",
    "rhs_weap_m249_pip_L_para",
    "rhs_weap_m249_pip_L_vfg",
    "rhs_weap_m240B",
    "rhs_weap_M590_8RD",
    "rhs_weap_M590_5RD",
    "rhs_weap_sr25",
    "rhs_weap_M136",
    "rhs_weap_M136_hedp",
    "rhs_weap_M136_hp",
    "rhs_weap_m72a7",
    "rhs_weap_smaw_green",
    "rhs_weap_m32_usmc",

    // Pistols
    "rhsusf_weap_m9",
    "rhsusf_weap_glock17g4",
    "rhsusf_weap_m1911a1",
    "hgun_ACPC2_F",

    // Binos
    "Binocular"
];

// Populate with predefined items
[_crate, _availableBackpacks] call BIS_fnc_addVirtualBackpackCargo;
[_crate, _availableItemCargo] call BIS_fnc_addVirtualItemCargo;
[_crate, _availableMagazines] call BIS_fnc_addVirtualMagazineCargo;
[_crate, _availableWeapons] call BIS_fnc_addVirtualWeaponCargo;
