{if ((typeOf _x == 'b_survivor_F') && (!isPlayer _x)) then {deleteVehicle _x}} forEach allUnits;
[MedicalData,3] call BIS_fnc_dataTerminalAnimate;
sleep 5;
_group1=createGroup west;
'b_survivor_F' createUnit [getmarkerPos 'PatientSpawn', _group1,'pat1=this; dostop pat1'];
[pat1, 'body', 0, objNull, selectRandom ['stab','bullet','falling'], 0, 0.70] call ace_medical_fnc_handleDamage_advanced;
[pat1, 'head', 0, objNull, selectRandom ['stab','bullet','falling'], 0, 0.60] call ace_medical_fnc_handleDamage_advanced;
[pat1, 'leg_l', 0, objNull, selectRandom ['stab','bullet','falling'], 0, 0.60] call ace_medical_fnc_handleDamage_advanced;
[pat1, 'body', 0, objNull, selectRandom ['stab','bullet','falling'], 0, 0.60] call ace_medical_fnc_handleDamage_advanced;
[pat1, 'leg_r', 0, objNull, selectRandom ['stab','bullet','falling'], 0, 0.60] call ace_medical_fnc_handleDamage_advanced;
[pat1, 'hand_r', 0, objNull, selectRandom ['stab','bullet','falling'], 0, 0.40] call ace_medical_fnc_handleDamage_advanced;
[pat1, 'hand_l', 0, objNull, selectRandom ['stab','bullet','falling'], 0, 0.40] call ace_medical_fnc_handleDamage_advanced;
[pat1] call ace_medical_fnc_handleDamage_advancedSetDamage;
[MedicalData,0] call BIS_fnc_dataTerminalAnimate;
hint 'Your patient is ready';